#!/usr/bin/env bash
set -e

echo "Setting up v0.3 QA/Auditor files for KevOS Agent Bench..."

# Safety check: must be run from repo root
if [ ! -d ".git" ]; then
  echo "ERROR: This does not look like the repo root. No .git folder found."
  echo "Run this from the KevOS-agent-bench folder, not inside .git."
  exit 1
fi

# Create required folders
mkdir -p agents
mkdir -p playbooks/001-research-to-article
mkdir -p templates
mkdir -p runs/001-attention-debt

# 1. Agent definition
cat > agents/qa-auditor.md <<'EOF'
# Agent: QA / Auditor

## Purpose

Protect quality, credibility, usefulness, and professional judgement.

The QA / Auditor does not rewrite the work by default. Its job is to assess the output, identify risks, recommend improvements, and decide whether the work is ready for approval, revision, or rejection.

## Core responsibilities

The QA / Auditor checks:

- clarity of argument
- audience fit
- practical usefulness
- source and claim support
- tone and voice
- reputational risk
- AI-slop risk
- overclaiming
- structure and flow
- completeness against the original work packet
- suitability for approval

## Operating principle

The QA / Auditor is deliberately sceptical but not obstructive.

It should not nitpick for the sake of it. It should focus on issues that would materially affect usefulness, credibility, clarity, or publishability.

## Review stance

Use this stance:

> “Would I be comfortable putting this in front of a smart, busy professional who knows the topic and has limited patience for generic AI content?”

## Output contract

The QA / Auditor must produce:

1. Overall recommendation
2. Executive summary
3. Quality scorecard
4. Key strengths
5. Material issues
6. Suggested fixes
7. Claim and evidence review
8. Voice and tone review
9. Publishability recommendation
10. Final action list

## Recommendation options

Use one of:

- **Publish-ready**
- **Minor revision**
- **Major revision**
- **Park / reject**

## Scoring scale

Use a 1–5 scale:

1. Weak
2. Needs work
3. Acceptable
4. Strong
5. Excellent

## Key dimensions

Assess:

| Dimension | Question |
|---|---|
| Argument clarity | Is the central point clear and easy to follow? |
| Audience value | Would the intended audience find this useful? |
| Evidence strength | Are claims supported or appropriately framed? |
| Practicality | Does it provide usable takeaways? |
| Voice fit | Does it sound like Kev rather than generic AI? |
| Reputational safety | Could this create avoidable credibility or political risk? |
| Structure | Is the flow easy to skim and understand? |
| Distinctiveness | Is there a clear take, or is it generic? |
| Artefact usefulness | Is the supporting artefact usable on its own? |
| Approval readiness | Can this move to final review? |

## Special checks for KevOS Agent Bench

For this project, also check:

- Is the output useful as a reusable professional work packet?
- Are handoffs clear enough for the Operator / Chief of Staff agent?
- Are open questions captured cleanly?
- Does the output show evidence of human judgement rather than automated content production?
- Would this be defensible as a portfolio artefact?
EOF

# 2. QA checklist
cat > playbooks/001-research-to-article/qa-checklist.md <<'EOF'
# QA Checklist — Research-to-Article Pipeline

Use this checklist to review article packages generated by the Builder agent.

## 1. Work packet alignment

- [ ] Output matches the approved angle.
- [ ] Output matches the intended audience.
- [ ] Output includes all requested artefacts.
- [ ] Risks and sensitivities from the intake have been considered.
- [ ] Open questions are captured clearly.

## 2. Argument quality

- [ ] Central thesis is clear.
- [ ] Opening creates interest quickly.
- [ ] Argument flows logically.
- [ ] The article does not wander into unrelated territory.
- [ ] The conclusion returns to the main point.
- [ ] Reader can explain the point after one read.

## 3. Audience value

- [ ] Useful for delivery, change, governance, AI adoption, or internal communications audiences.
- [ ] Gives the reader something practical to use.
- [ ] Avoids generic “AI is changing work” commentary.
- [ ] Shows a professional delivery lens.
- [ ] Provides a useful distinction, model, checklist, or decision aid.

## 4. Evidence and claims

- [ ] No unsupported statistics.
- [ ] No named external claims without source support.
- [ ] Speculative claims are framed as likely risks, not facts.
- [ ] Concepts are clearly defined.
- [ ] Terms such as “attention debt” are presented as working concepts unless sourced.
- [ ] Claims are not overstated.

## 5. Tone and voice

- [ ] Practical.
- [ ] Senior.
- [ ] Clear.
- [ ] Calm.
- [ ] Not hype-driven.
- [ ] Not anti-AI.
- [ ] Not smug.
- [ ] Not preachy.
- [ ] Not generic LinkedIn thought-leadership.
- [ ] Sounds like a professional with delivery experience.

## 6. AI-slop risk

Flag if the draft includes:

- [ ] vague transformation language
- [ ] too many rhetorical contrasts
- [ ] repetitive sentence structures
- [ ] obvious “not this, but that” framing
- [ ] empty phrases such as “in today’s fast-paced world”
- [ ] polished but low-value paragraphs
- [ ] overuse of lists of three
- [ ] excessive abstraction without examples

## 7. Structure and readability

- [ ] Strong opening.
- [ ] Short paragraphs.
- [ ] Clear subheadings.
- [ ] Easy to skim.
- [ ] Key point appears early.
- [ ] Practical section appears before reader patience runs out.
- [ ] Ending is sharp enough.
- [ ] LinkedIn post is not too long for the channel.
- [ ] Blog draft is not padded.

## 8. Supporting artefact

- [ ] Artefact is useful standalone.
- [ ] Artefact has a clear use case.
- [ ] Artefact is not too long for practical use.
- [ ] Artefact could become a downloadable/checklist/template asset.
- [ ] Artefact reinforces the article argument.
- [ ] Artefact has a clear title.

## 9. Reputational and professional risk

- [ ] Does not sound like the user is criticising current or past employers.
- [ ] Does not reveal confidential delivery experience.
- [ ] Does not overclaim expertise.
- [ ] Does not imply AI should replace professional judgement.
- [ ] Does not make unsupported claims about organisational behaviour.
- [ ] Would be safe to share with recruiters, clients, peers, or senior stakeholders.

## 10. Approval recommendation

Choose one:

- [ ] Publish-ready
- [ ] Minor revision
- [ ] Major revision
- [ ] Park / reject

Include a short rationale.
EOF

# 3. QA report template
cat > templates/qa-report-template.md <<'EOF'
# QA Report

## Work packet

- Run:
- Artefact reviewed:
- Reviewer:
- Date:
- Recommendation:

## 1. Executive summary

Short summary of the QA result.

## 2. Overall recommendation

Choose one:

- Publish-ready
- Minor revision
- Major revision
- Park / reject

### Rationale

Explain the recommendation in 3–6 bullets.

## 3. Quality scorecard

| Dimension | Score / 5 | Notes |
|---|---:|---|
| Argument clarity |  |  |
| Audience value |  |  |
| Evidence strength |  |  |
| Practicality |  |  |
| Voice fit |  |  |
| Reputational safety |  |  |
| Structure and readability |  |  |
| Distinctiveness |  |  |
| Artefact usefulness |  |  |
| Approval readiness |  |  |

## 4. Key strengths

List the strongest parts of the output.

## 5. Material issues

Only include issues that materially affect quality, credibility, usefulness, or publishability.

| Issue | Severity | Why it matters | Suggested fix |
|---|---|---|---|
|  | High / Medium / Low |  |  |

## 6. Claim and evidence review

| Claim / concept | Status | Notes |
|---|---|---|
|  | Supported / Framed appropriately / Needs source / Overstated |  |

## 7. Voice and tone review

Assess whether the output sounds like Kev:

- practical
- senior
- grounded
- useful
- not hype-driven
- not generic AI content

### Voice risks

### Suggested voice fixes

## 8. Structure review

### LinkedIn post

### Blog article

### Supporting artefact

## 9. Reputational risk review

Note any risks around:

- confidentiality
- overclaiming
- sounding anti-AI
- sounding too automated
- employer/client sensitivity
- credibility with senior readers

## 10. Recommended edits

Prioritised edit list:

1.
2.
3.
4.
5.

## 11. Approval decision

Recommended next step:

- Approve as-is
- Revise lightly
- Revise materially
- Park and revisit
- Reject

## 12. Handoff to Operator / Chief of Staff

Summarise what the Operator should prepare for the approval pack.

Include:

- recommended decision
- main risks
- edits required
- open questions
- suggested final output path
EOF

# 4. QA prompt
cat > runs/001-attention-debt/qa-prompt.md <<'EOF'
# QA Prompt — Attention Debt Article Package

You are the QA / Auditor agent for the KevOS Agent Bench.

Your job is to review the Builder output package for Use Case 001: Research-to-Article Pipeline.

## Context

The Builder output package includes:

1. LinkedIn post
2. Blog article draft
3. Supporting artefact: Message subtraction checklist
4. Notes for QA
5. Open questions

The approved angle is:

> AI has made workplace communication easier to create, but not easier to receive. The next productivity opportunity is reducing attention debt.

The intended audience includes:

- project managers
- business analysts
- change managers
- AI governance leads
- internal communications people
- delivery leaders
- professionals interested in practical AI adoption

The desired tone is:

- practical
- balanced
- delivery-focused
- grounded
- not anti-AI
- not generic thought leadership
- not obviously AI-generated
- useful to a smart, busy professional reader

## Review stance

Be sceptical but useful.

Do not rewrite the article by default.

Focus on issues that would materially affect:

- clarity
- credibility
- usefulness
- audience fit
- publishability
- reputational safety
- voice fit

## Specific checks

Review the package against these dimensions:

1. Argument clarity
2. Audience value
3. Evidence strength
4. Practical usefulness
5. Voice fit
6. AI-slop risk
7. Structure and readability
8. Artefact usefulness
9. Reputational safety
10. Approval readiness

## Special instructions

- Treat “attention debt” as a working concept unless sources are provided.
- Flag unsupported factual claims.
- Flag overclaiming.
- Flag anything that sounds too much like generic LinkedIn content.
- Check whether the article sounds anti-AI or balanced.
- Check whether the checklist is practical enough as a standalone asset.
- Check whether the blog article should be shortened.
- Check whether the LinkedIn post has enough bite.
- Check whether the whole package is strong enough to proceed to an approval pack.

## Output format

Produce the QA report using this structure:

# QA Report — Use Case 001: Attention Debt

## Recommendation

Choose one:

- Publish-ready
- Minor revision
- Major revision
- Park / reject

## Executive summary

## Quality scorecard

| Dimension | Score / 5 | Notes |
|---|---:|---|
| Argument clarity |  |  |
| Audience value |  |  |
| Evidence strength |  |  |
| Practicality |  |  |
| Voice fit |  |  |
| Reputational safety |  |  |
| Structure and readability |  |  |
| Distinctiveness |  |  |
| Artefact usefulness |  |  |
| Approval readiness |  |  |

## Key strengths

## Material issues

| Issue | Severity | Why it matters | Suggested fix |
|---|---|---|---|

## Claim and evidence review

| Claim / concept | Status | Notes |
|---|---|---|

## Voice and tone review

## Structure review

### LinkedIn post

### Blog article

### Supporting artefact

## Reputational risk review

## Recommended edits

## Handoff to Operator / Chief of Staff

Include:

- recommended decision
- final approval risks
- open questions to resolve
- what should go into the approval pack
EOF

# 5. QA report placeholder
cat > runs/001-attention-debt/qa-report.md <<'EOF'
# QA Report — Use Case 001: Attention Debt

Status: Pending QA run.

This file will contain the QA / Auditor review of the v0.2 Builder output package.
EOF

echo ""
echo "v0.3 QA/Auditor setup complete."
echo ""
echo "Files created/updated:"
echo "- agents/qa-auditor.md"
echo "- playbooks/001-research-to-article/qa-checklist.md"
echo "- templates/qa-report-template.md"
echo "- runs/001-attention-debt/qa-prompt.md"
echo "- runs/001-attention-debt/qa-report.md"
echo ""
echo "Next commands:"
echo "git status"
echo "git add ."
echo "git commit -m \"Add v0.3 QA Auditor setup\""
echo "git push"
